# Copyright @ 2023 Thought Machine Group Limited. All rights reserved.
---
resources:
  - id: LOAN_APPLICATION
    instantiation_resources:
      - Customer
  - id: LOAN_REPAYMENT_HOLIDAY_APPLICATION
    instantiation_resources:
      - Customer account
