from inception_sdk.test_framework.common.constants import ASSET, LIABILITY

# Accounts
TIME_DEPOSIT_MDH = "TIME_DEPOSIT_MDH"

# Internal accounts
PARAM_ACCRUED_PROFIT_PAYABLE_ACCOUNT = "ACCRUED_PROFIT_PAYABLE_ACCOUNT"
PARAM_PROFIT_PAID_ACCOUNT = "PROFIT_PAID_ACCOUNT"
PARAM_ZAKAT_RECEIVABLE_ACOUNT = "ZAKAT_RECEIVABLE_ACOUNT"
PARAM_TAX_RECEIVABLE_ACOUNT = "TAX_RECEIVABLE_ACOUNT"
INTERNAL_SUSPENSE_ACOCUNT = "SUSPENSE_ACCOUNT"
INTERNAL_DISBURSEMENT_ACOCUNT = "DISBURSEMENT_ACCOUNT"

default_internal_accounts = {
    PARAM_ACCRUED_PROFIT_PAYABLE_ACCOUNT: LIABILITY,
    PARAM_PROFIT_PAID_ACCOUNT: LIABILITY,
    PARAM_ZAKAT_RECEIVABLE_ACOUNT: ASSET,
    PARAM_TAX_RECEIVABLE_ACOUNT: ASSET,
    INTERNAL_SUSPENSE_ACOCUNT: LIABILITY,
    INTERNAL_DISBURSEMENT_ACOCUNT: LIABILITY,
}